//@GeneratedCode
/*****************************************************************************************
  Please note that this file is regenerated each time it is generated
  and all your changes will be overwritten in this file.
  If you still want to make changes, you can do this in 2 ways:
  
  1. Use a 'partial class name' according to the following pattern:
  
  #if GENERATEDCODE_ON
  namespace_name {
    partial class ClassName
    {
      partial void BeforeExecute(ref bool handled)
      {
        //... do something
        handled = true;
      }
    }
   }
  #endif
  
  2. Change the label //@GeneratedCode to //@CustomizedCode, for example.
     Alternatively, you can also remove the label or give it a different name.
*****************************************************************************************/
namespace SEMusicStoreBase.WebApi.Models
{
    using System;
    /// <summary>
    /// Generated by the generator.
    /// </summary>
    public partial class TrackEdit
    {
        /// <summary>
        /// Initializes the class (created by the generator).
        /// </summary>
        static TrackEdit()
        {
            ClassConstructing();
            ClassConstructed();
        }
        /// <summary>
        /// This method is called before the construction of the class.
        /// </summary>
        static partial void ClassConstructing();
        /// <summary>
        /// This method is called when the class is constructed.
        /// </summary>
        static partial void ClassConstructed();

        /// <summary>
        /// Initializes a new instance of the <see cref="TrackEdit"/> class (created by the generator.)
        /// </summary>
        public TrackEdit()
        {
            Constructing();

            Constructed();
        }
        /// <summary>
        /// This method is called the object is being constraucted.
        /// </summary>
        partial void Constructing();
        /// <summary>
        /// This method is called when the object is constructed.
        /// </summary>
        partial void Constructed();
        /// <summary>
        /// Property 'AlbumId' generated by the generator.
        /// </summary>
        /// <summary>
        /// Property 'AlbumId' generated by the generator.
        /// </summary>
        public IdType AlbumId { get; set; }
        /// <summary>
        /// Property 'GenreId' generated by the generator.
        /// </summary>
        /// <summary>
        /// Property 'GenreId' generated by the generator.
        /// </summary>
        public IdType GenreId { get; set; }
        /// <summary>
        /// Property 'Title' generated by the generator.
        /// </summary>
        /// <summary>
        /// Property 'Title' generated by the generator.
        /// </summary>
        public System.String Title { get; set; } = string.Empty;
        /// <summary>
        /// Property 'Composer' generated by the generator.
        /// </summary>
        /// <summary>
        /// Property 'Composer' generated by the generator.
        /// </summary>
        public System.String Composer { get; set; } = string.Empty;
        /// <summary>
        /// Property 'Milliseconds' generated by the generator.
        /// </summary>
        /// <summary>
        /// Property 'Milliseconds' generated by the generator.
        /// </summary>
        public System.Int64 Milliseconds { get; set; }
        /// <summary>
        /// Property 'Bytes' generated by the generator.
        /// </summary>
        /// <summary>
        /// Property 'Bytes' generated by the generator.
        /// </summary>
        public System.Int64 Bytes { get; set; }
        /// <summary>
        /// Property 'UnitPrice' generated by the generator.
        /// </summary>
        /// <summary>
        /// Property 'UnitPrice' generated by the generator.
        /// </summary>
        public System.Double UnitPrice { get; set; }
        /// <summary>
        /// Property 'Album' generated by the generator.
        /// </summary>
        /// <summary>
        /// Property 'Album' generated by the generator.
        /// </summary>
        public SEMusicStoreBase.WebApi.Models.Album? Album { get; set; }
        /// <summary>
        /// Property 'Genre' generated by the generator.
        /// </summary>
        /// <summary>
        /// Property 'Genre' generated by the generator.
        /// </summary>
        public SEMusicStoreBase.WebApi.Models.Genre? Genre { get; set; }
    }
}
