//@GeneratedCode
/*****************************************************************************************
  Please note that this file is regenerated each time it is generated
  and all your changes will be overwritten in this file.
  If you still want to make changes, you can do this in 2 ways:
  
  1. Use a 'partial class name' according to the following pattern:
  
  #if GENERATEDCODE_ON
  namespace_name {
    partial class ClassName
    {
      partial void BeforeExecute(ref bool handled)
      {
        //... do something
        handled = true;
      }
    }
   }
  #endif
  
  2. Change the label //@GeneratedCode to //@CustomizedCode, for example.
     Alternatively, you can also remove the label or give it a different name.
*****************************************************************************************/
namespace SEMusicStoreBase.Logic.DataContext
{
    /// <summary>
    /// Generated by the generator
    /// </summary>
    partial class ProjectDbContext
    {
        #region properties
        /// <summary>
        /// Generated by the generator.
        /// </summary>
        private DbSet<Entities.Album> DbAlbumSet { get; set; }
        /// <summary>
        /// Generated by the generator.
        /// </summary>
        public Contracts.IAlbumSet AlbumSet => (Contracts.IAlbumSet)GetEntitySet<Entities.Album>();
        /// <summary>
        /// Generated by the generator.
        /// </summary>
        private DbSet<Entities.Artist> DbArtistSet { get; set; }
        /// <summary>
        /// Generated by the generator.
        /// </summary>
        public Contracts.IArtistSet ArtistSet => (Contracts.IArtistSet)GetEntitySet<Entities.Artist>();
        /// <summary>
        /// Generated by the generator.
        /// </summary>
        private DbSet<Entities.Genre> DbGenreSet { get; set; }
        /// <summary>
        /// Generated by the generator.
        /// </summary>
        public Contracts.IGenreSet GenreSet => (Contracts.IGenreSet)GetEntitySet<Entities.Genre>();
        /// <summary>
        /// Generated by the generator.
        /// </summary>
        private DbSet<Entities.Track> DbTrackSet { get; set; }
        /// <summary>
        /// Generated by the generator.
        /// </summary>
        public Contracts.ITrackSet TrackSet => (Contracts.ITrackSet)GetEntitySet<Entities.Track>();
        #endregion properties

        #region partial methods
        /// <summary>
        /// Generated by the generator
        /// </summary>
        partial void GetGeneratorDbSet<E>(ref DbSet<E>? dbSet, ref bool handled) where E : Entities.DbObject
        {
            if (typeof(E) == typeof(Entities.Album))
            {
                dbSet = DbAlbumSet as DbSet<E>;
                handled = true;
            }
            else if (typeof(E) == typeof(Entities.Artist))
            {
                dbSet = DbArtistSet as DbSet<E>;
                handled = true;
            }
            else if (typeof(E) == typeof(Entities.Genre))
            {
                dbSet = DbGenreSet as DbSet<E>;
                handled = true;
            }
            else if (typeof(E) == typeof(Entities.Track))
            {
                dbSet = DbTrackSet as DbSet<E>;
                handled = true;
            }
        }
        /// <summary>
        /// Generated by the generator
        /// </summary>
        partial void GetGeneratorEntitySet<E>(ref EntitySet<E>? entitySet, ref bool handled) where E : Entities.EntityObject, new()
        {
            if (typeof(E) == typeof(Entities.Album))
            {
                entitySet = new DataContext.AlbumSet(this, DbAlbumSet) as EntitySet<E>;
                handled = true;
            }
            else if (typeof(E) == typeof(Entities.Artist))
            {
                entitySet = new DataContext.ArtistSet(this, DbArtistSet) as EntitySet<E>;
                handled = true;
            }
            else if (typeof(E) == typeof(Entities.Genre))
            {
                entitySet = new DataContext.GenreSet(this, DbGenreSet) as EntitySet<E>;
                handled = true;
            }
            else if (typeof(E) == typeof(Entities.Track))
            {
                entitySet = new DataContext.TrackSet(this, DbTrackSet) as EntitySet<E>;
                handled = true;
            }
        }
        /// <summary>
        /// Generated by the generator
        /// </summary>
        partial void GetGeneratorViewSet<E>(ref ViewSet<E>? viewSet, ref bool handled) where E : Entities.ViewObject, new()
        {
        }
        /// <summary>
        /// Generated by the generator
        /// </summary>
        static partial void OnViewModelCreating(ModelBuilder modelBuilder)
        {
        }
        #endregion partial methods
    }
}
