//@GeneratedCode
/*****************************************************************************************
  Please note that this file is regenerated each time it is generated
  and all your changes will be overwritten in this file.
  If you still want to make changes, you can do this in 2 ways:
  
  1. Use a 'partial class name' according to the following pattern:
  
  #if GENERATEDCODE_ON
  namespace_name {
    partial class ClassName
    {
      partial void BeforeExecute(ref bool handled)
      {
        //... do something
        handled = true;
      }
    }
   }
  #endif
  
  2. Change the label //@GeneratedCode to //@CustomizedCode, for example.
     Alternatively, you can also remove the label or give it a different name.
*****************************************************************************************/
namespace SEMusicStoreBase.MVVMApp.Models
{
    using System;
    /// <summary>
    /// This model represents a transmission model for the 'Artist' data unit.
    /// </summary>

    public partial class Artist : SEMusicStoreBase.Common.Contracts.IArtist
    {
        /// <summary>
        /// Initializes the class (created by the generator).
        /// </summary>
        static Artist()
        {
            ClassConstructing();
            ClassConstructed();
        }
        /// <summary>
        /// This method is called before the construction of the class.
        /// </summary>
        static partial void ClassConstructing();
        /// <summary>
        /// This method is called when the class is constructed.
        /// </summary>
        static partial void ClassConstructed();

        /// <summary>
        /// Initializes a new instance of the <see cref="Artist"/> class (created by the generator.)
        /// </summary>
        public Artist()
        {
            Constructing();

            Constructed();
        }
        /// <summary>
        /// This method is called the object is being constraucted.
        /// </summary>
        partial void Constructing();
        /// <summary>
        /// This method is called when the object is constructed.
        /// </summary>
        partial void Constructed();
        /// <summary>
        /// Property 'Name' generated by the generator.
        /// </summary>
        public System.String Name { get; set; } = string.Empty;
        /// <summary>
        /// Determines whether the specified object is equal to the current object.
        /// </summary>
        /// <param name="obj">The object to compare with the current object.</param>
        public override bool Equals(object? obj)
        {
            bool result = false;
            if (obj is Models.Artist other)
            {
                result = base.Equals(other) && IsEqualsWith(Name, other.Name);
            }
            return result;
        }
        /// <summary>
        /// Serves as the default hash function.
        /// </summary>
        public override int GetHashCode()
        {
            return this.CalculateHashCode(base.GetHashCode(), Name);
        }
    }
}
