//@GeneratedCode
@startuml SEMusicStoreBase.Logic.Entities.Album
+class Album #whitesmoke {
    - Int32 _artistId
    - String _title
    - Artist _artist
    - List<Track> _tracks
    ---
     + Int32 getArtistId()
     + setArtistId(Int32 value)
     + String getTitle()
     + setTitle(String value)
     + Artist getArtist()
     + setArtist(Artist value)
     + List<Track> getTracks()
     + setTracks(List<Track> value)
    ---
    + Int32 get_ArtistId()
    + Void set_ArtistId(Int32 value)
    + String get_Title()
    + Void set_Title(String value)
    + Artist get_Artist()
    + Void set_Artist(Artist value)
    + List<Track> get_Tracks()
    + Void set_Tracks(List`1 value)
    + String ToString()
}
+abstract class VersionEntityObject #white {
}
+abstract class EntityObject #white {
    - Int32 _id
    ---
     + Int32 getId()
     + setId(Int32 value)
    ---
    + Int32 get_Id()
    + Void set_Id(Int32 value)
}
+abstract class DbObject #white {
}
interface IIdentifiable #lightgrey {
     + Int32 getId()
     + setId(Int32 value)
    ---
    + Int32 get_Id()
    + Void set_Id(Int32 value)
    + Void CopyProperties(IIdentifiable other)
}
VersionEntityObject <|-- Album
EntityObject <|-- VersionEntityObject
DbObject <|-- EntityObject
IIdentifiable ()- EntityObject
Album --> "0..1" Artist
Album "*" o-- "0..1" Track
@enduml
