//@GeneratedCode
@startuml SEMusicStoreBase.Logic.Entities.Genre
+class Genre #whitesmoke {
    - String _name
    - List<Track> _tracks
    ---
     + String getName()
     + setName(String value)
     + List<Track> getTracks()
     + setTracks(List<Track> value)
    ---
    + String get_Name()
    + Void set_Name(String value)
    + List<Track> get_Tracks()
    + Void set_Tracks(List`1 value)
    + String ToString()
}
+abstract class VersionEntityObject #white {
}
+abstract class EntityObject #white {
    - Int32 _id
    ---
     + Int32 getId()
     + setId(Int32 value)
    ---
    + Int32 get_Id()
    + Void set_Id(Int32 value)
}
+abstract class DbObject #white {
}
interface IIdentifiable #lightgrey {
     + Int32 getId()
     + setId(Int32 value)
    ---
    + Int32 get_Id()
    + Void set_Id(Int32 value)
    + Void CopyProperties(IIdentifiable other)
}
VersionEntityObject <|-- Genre
EntityObject <|-- VersionEntityObject
DbObject <|-- EntityObject
IIdentifiable ()- EntityObject
Genre "*" o-- "0..1" Track
@enduml
