//@GeneratedCode
@startuml SEMusicStoreBase.Logic.Entities.Track
+class Track #whitesmoke {
    - Int32 _albumId
    - Int32 _genreId
    - String _title
    - String _composer
    - Int64 _milliseconds
    - Int64 _bytes
    - Double _unitPrice
    - Album _album
    - Genre _genre
    ---
     + Int32 getAlbumId()
     + setAlbumId(Int32 value)
     + Int32 getGenreId()
     + setGenreId(Int32 value)
     + String getTitle()
     + setTitle(String value)
     + String getComposer()
     + setComposer(String value)
     + Int64 getMilliseconds()
     + setMilliseconds(Int64 value)
     + Int64 getBytes()
     + setBytes(Int64 value)
     + Double getUnitPrice()
     + setUnitPrice(Double value)
     + Album getAlbum()
     + setAlbum(Album value)
     + Genre getGenre()
     + setGenre(Genre value)
    ---
    + Int32 get_AlbumId()
    + Void set_AlbumId(Int32 value)
    + Int32 get_GenreId()
    + Void set_GenreId(Int32 value)
    + String get_Title()
    + Void set_Title(String value)
    + String get_Composer()
    + Void set_Composer(String value)
    + Int64 get_Milliseconds()
    + Void set_Milliseconds(Int64 value)
    + Int64 get_Bytes()
    + Void set_Bytes(Int64 value)
    + Double get_UnitPrice()
    + Void set_UnitPrice(Double value)
    + Album get_Album()
    + Void set_Album(Album value)
    + Genre get_Genre()
    + Void set_Genre(Genre value)
    + String ToString()
}
+abstract class VersionEntityObject #white {
}
+abstract class EntityObject #white {
    - Int32 _id
    ---
     + Int32 getId()
     + setId(Int32 value)
    ---
    + Int32 get_Id()
    + Void set_Id(Int32 value)
}
+abstract class DbObject #white {
}
interface IIdentifiable #lightgrey {
     + Int32 getId()
     + setId(Int32 value)
    ---
    + Int32 get_Id()
    + Void set_Id(Int32 value)
    + Void CopyProperties(IIdentifiable other)
}
VersionEntityObject <|-- Track
EntityObject <|-- VersionEntityObject
DbObject <|-- EntityObject
IIdentifiable ()- EntityObject
Track --> "0..1" Album
Track --> "0..1" Genre
@enduml
